In [2]:
import numpy as np


# Q1  Write a NumPy program to create an array with the values 1, 7, 13, 105    and determine the size of the memory occupied by the array.

In [3]:
arr=np.array([1,7,13,15])
print(f"size of array :{arr.size}")
print(f"type:{arr.dtype}")
print(f"size of item :{arr.itemsize}")
print(f"memory :{arr.nbytes}")

size of array :4
type:int64
size of item :8
memory :32


# Q2  Write a NumPy program to create an element-wise comparison (greater,    greater_equal, less and less_equal) of two given arrays.

In [65]:
arr1=np.array([3,5,6,8])
arr2=np.array([4,5,5,9])
print(arr1)
print(arr2)
print(np.greater(arr1,arr2))
print(np.greater_equal(arr1,arr2))      
print(np.less(arr1,arr2))
print(np.less_equal(arr1,arr2))

[3 5 6 8]
[4 5 5 9]
[False False  True False]
[False  True  True False]
[ True False False  True]
[ True  True False  True]


# Q3 Write a NumPy program to create an array of 10 zeros, 10 ones, 10    fives, 10 tens, 10 twentys and 10 fiftys.

In [66]:
arr1=np.zeros(10)
print(arr1)
arr1=np.ones(10)
print(arr1)
print(arr1*5)
print(arr1*10)
print(arr1*20)
print(arr1*50)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
[5. 5. 5. 5. 5. 5. 5. 5. 5. 5.]
[10. 10. 10. 10. 10. 10. 10. 10. 10. 10.]
[20. 20. 20. 20. 20. 20. 20. 20. 20. 20.]
[50. 50. 50. 50. 50. 50. 50. 50. 50. 50.]


# Q4 Write a NumPy program to create an array of integers from 30 to 70.

In [67]:
arr=np.arange(30,70)
print(arr)

[30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50 51 52 53
 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69]


# Q5  Write a NumPy program to create an array of integers from 50 to 95.

In [68]:
arr=np.arange(50,95)
print(arr)

[50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71 72 73
 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94]


# Q6 Write a NumPy program to create an array of all even integers from 20 to 80.

In [69]:
arr=np.arange(20,80,2)
print(arr)

[20 22 24 26 28 30 32 34 36 38 40 42 44 46 48 50 52 54 56 58 60 62 64 66
 68 70 72 74 76 78]


# Q7 Write a NumPy program to create an array of all odd integers from 20 to 80.

In [70]:
arr=np.arange(21,80,2)
print(arr)

[21 23 25 27 29 31 33 35 37 39 41 43 45 47 49 51 53 55 57 59 61 63 65 67
 69 71 73 75 77 79]


# Q8 Write a NumPy program to generate an array of 15 random numbers from 10    to 40.

In [71]:
arr=np.random.randint(10,40,15)
print(arr)

[12 36 12 18 28 10 30 26 35 11 38 12 27 34 12]


# Q9 Write a NumPy program to generate an array of 10 random numbers from 30    to 50.

In [72]:
arr=np.random.randint(30,50,10)
print(arr)

[37 46 44 41 40 35 38 40 38 46]


# Q10 Write a NumPy program to generate an array of 20 random numbers from 50    to 90.

In [73]:
arr=np.random.randint(50,90,20)
print(arr)

[71 72 63 75 88 55 70 69 83 50 75 82 86 87 65 57 86 58 82 87]


# Q11  Create any two arrays & perform various mathematical operations. i.e. Addition, Substraction, Multiplication, Divide.


In [74]:
arr1=np.array([11,22,33,44,55])
arr2=np.array([1,2,3,4,4])
print(arr1+arr2)
print(arr1-arr2)
print(arr1*arr2)
print(arr1/arr2)

[12 24 36 48 59]
[10 20 30 40 51]
[ 11  44  99 176 220]
[11.   11.   11.   11.   13.75]


# Q12 Write a NumPy program to create a 3x4 matrix filled with values from 10     to 21.

In [75]:
arr=(np.arange(10,22).reshape(3,4))
print(arr)

[[10 11 12 13]
 [14 15 16 17]
 [18 19 20 21]]


# Q13  Write a NumPy program to create a 3x3 identity matrix, i.e. the diagonal     elements are 1, the rest are 0.

In [76]:
arr=np.eye(3)
print(arr)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


# Q14 Write a NumPy program to find the number of rows and columns in a given     matrix

In [77]:
arr=(np.arange(10,22).reshape(3,4))
print(arr)
print(arr.shape)

[[10 11 12 13]
 [14 15 16 17]
 [18 19 20 21]]
(3, 4)


# Q15 Write a NumPy program to create a 5x5 zero matrix with elements on the     main diagonal equal to 1, 2, 3, 4, 5.

In [78]:
arr=np.diag([1,2,3,4,5])
print(arr)

[[1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]
 [0 0 0 0 5]]


# Q16  Write a NumPy program to create a 3x3x3 array filled with arbitrary     values.

In [79]:
arr=np.random.random((3, 3, 3))
print(arr)

[[[0.14019962 0.76488781 0.27292408]
  [0.89404596 0.49165308 0.65435194]
  [0.43231938 0.83850861 0.18036871]]

 [[0.44060949 0.61088466 0.90162636]
  [0.6675502  0.32427913 0.6927056 ]
  [0.44365989 0.83963205 0.2900461 ]]

 [[0.7694377  0.56476688 0.83374497]
  [0.82986622 0.24867637 0.08551785]
  [0.91385695 0.99309942 0.65017486]]]


# Q17 Write a NumPy program to create a 2x3x4 array filled with arbitrary     values

In [80]:
arr=np.random.random((2,3,4))
print(arr)

[[[0.64050519 0.02238706 0.97741641 0.32795206]
  [0.19511578 0.52079507 0.79088579 0.82466058]
  [0.49720676 0.86491457 0.85448878 0.03049573]]

 [[0.97099538 0.58925403 0.73619096 0.36679442]
  [0.40766596 0.23592639 0.49899062 0.77930784]
  [0.42877101 0.21485133 0.81806481 0.63245361]]]


# Q18  Write a NumPy program to convert a list of numeric values into a one-    dimensional NumPy array.

In [81]:
list=[12,121,34.56,78,89]
print(list)
print(type(list))
arr=np.array(list)
print(arr)
print(type(arr))


[12, 121, 34.56, 78, 89]
<class 'list'>
[ 12.   121.    34.56  78.    89.  ]
<class 'numpy.ndarray'>


# Q19 Write a NumPy program to create a 3x3 matrix with values ranging from 2     to 10.

In [82]:
arr=(np.arange(2,11).reshape(3,3))
print(arr)

[[ 2  3  4]
 [ 5  6  7]
 [ 8  9 10]]


# Q20 Write a NumPy program to create an array with values ranging from 12 to 38.

In [83]:
arr=np.arange(12,38)
print(arr)

[12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35
 36 37]


# Q21 Write a NumPy program to reverse an array (the first element becomes the last).

In [84]:
arr=np.array([12,13,14,15,16])
arr=arr[::-1]
print(arr)

[16 15 14 13 12]


# Q22 Write a NumPy program to convert an data type into to a floating type.

In [85]:
arr=np.array([11,22,33,44,55])
print(arr.dtype)
arr=np.array([11,22,33,44,55],dtype=np.float16)
print(arr.dtype)

int64
float16


# Q23  Write a NumPy program to convert a list array

In [86]:

list=[12,121,34.56,78,89]
print(list)
print(type(list))
arr=np.array(list)
print(arr)
print(type(arr))


[12, 121, 34.56, 78, 89]
<class 'list'>
[ 12.   121.    34.56  78.    89.  ]
<class 'numpy.ndarray'>


# Q24 Write a NumPy program to get the element-wise remainder of an array of division.

In [87]:
arr=np.arange(10)
print(arr)
arr=np.remainder(arr,5)
print(arr)

[0 1 2 3 4 5 6 7 8 9]
[0 1 2 3 4 0 1 2 3 4]


# Q25 Write a NumPy program to get the element-wise remainder of an array of numbers from 20 to 50 which are divisible by 3.

In [88]:
arr=np.arange(20,50)
print(arr)
arr=np.remainder(arr,3)
print(arr)

[20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43
 44 45 46 47 48 49]
[2 0 1 2 0 1 2 0 1 2 0 1 2 0 1 2 0 1 2 0 1 2 0 1 2 0 1 2 0 1]
